export enum CHANNEL_TYPE {
  DIRECT = 'DIRECT',
  CHANNEL_PUBLIC = 'CHANNEL_PUBLIC',
  CHANNEL_PRIVATE = 'CHANNEL_PRIVATE',
}

export const CHANGE_TYPE_VALUE = {
  ADDED: 'ADDED',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
};

export enum EVENT_TYPE {
  ADDED = 'ADDED',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  COUNT = 'COUNT',
}

export type eventType = 'ADDED' | 'UPDATE' | 'DELETE';

export enum EVENT_TYPE_ENUM {
  CHANNEL_CHANGE = 'CHANNEL_CHANGE',
  MESSAGE_COUNT_CHANGE = 'MESSAGE_COUNT_CHANGE',
}

export const EVENT_TYPE_VALUES = {
  CHANNEL_CHANGE: 'CHANNEL_CHANGE',
  MESSAGE_COUNT_CHANGE: 'MESSAGE_COUNT_CHANGE',
};
